# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-11-16 02:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('logo', models.ImageField(default='associations/default.png', upload_to='associations', verbose_name='Logo')),
                ('type_a', models.CharField(choices=[('GOVERMENT', 'Government'), ('PRIVATE', 'Private'), ('MIXED', 'Mixed'), ('OTHERS', 'Others')], default='PRIVATE', max_length=10, verbose_name='Type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_actived', models.BooleanField(default=False, verbose_name='Actived')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Association',
                'verbose_name_plural': 'Associations',
                'permissions': (('association', 'Can ALL association'),),
            },
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('logo', models.ImageField(default='enterprises/default.png', upload_to='enterprises', verbose_name='Logo')),
                ('tax_id', models.CharField(max_length=50, verbose_name='Tax id')),
                ('type_e', models.CharField(choices=[('GOVERMENT', 'Government'), ('PRIVATE', 'Private'), ('MIXED', 'Mixed'), ('OTHERS', 'Others')], default='PRIVATE', max_length=10, verbose_name='Type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_actived', models.BooleanField(default=False, verbose_name='Actived')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Enterprise',
                'verbose_name_plural': 'Enterprises',
                'permissions': (('enterprise', 'Can ALL enterprise'),),
            },
        ),
        migrations.CreateModel(
            name='Headquar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('is_main', models.BooleanField(default=False, verbose_name='Main')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_actived', models.BooleanField(default=False, verbose_name='Actived')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('association', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='space.Association', verbose_name='Association')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space.Enterprise', verbose_name='Enterprise')),
            ],
            options={
                'verbose_name': 'Headquar',
                'verbose_name_plural': 'Headquars',
                'permissions': (('headquar', 'Can ALL headquar(sedes)'),),
            },
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Price')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('test_image', models.ImageField(blank=True, default='test_images/default.png', null=True, upload_to='test_images', verbose_name='Test image')),
                ('test_date', models.DateTimeField(blank=True, null=True, verbose_name='Test date')),
            ],
            options={
                'verbose_name': 'Solution',
                'verbose_name_plural': 'Solutions',
                'permissions': (('solution', 'Can ALL solution'),),
            },
        ),
        migrations.AlterUniqueTogether(
            name='solution',
            unique_together=set([('name',)]),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='solution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='space.Solution', verbose_name='Solution'),
        ),
        migrations.AddField(
            model_name='association',
            name='solution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='space.Solution', verbose_name='Solution'),
        ),
        migrations.AlterUniqueTogether(
            name='headquar',
            unique_together=set([('name', 'enterprise')]),
        ),
        migrations.AlterUniqueTogether(
            name='enterprise',
            unique_together=set([('name', 'tax_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='association',
            unique_together=set([('name',)]),
        ),
    ]
