# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-11-16 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_type', models.CharField(choices=[('NID', 'N.I.D.'), ('FC', 'Foreign card'), ('CB', 'Certificate birth'), ('OTHER', 'Other')], default='NID', max_length=10, verbose_name='Identity type')),
                ('identity_num', models.CharField(blank=True, error_messages={'unique': 'eeeee ee'}, max_length=20, null=True, verbose_name='Identity num')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Last name')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='birth date')),
                ('photo', models.ImageField(blank=True, default='persons/default.png', null=True, upload_to='persons', verbose_name='Photo')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
            },
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together=set([('identity_type', 'identity_num'), ('first_name', 'last_name', 'identity_type', 'identity_num')]),
        ),
    ]
