# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-11-16 02:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AntecedenteMedico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antecedente_morbidos', models.TextField(blank=True, null=True, verbose_name='Antecedentes mórbidos')),
                ('antecedente_ginecoobstetrico', models.TextField(blank=True, null=True, verbose_name='Antecedentes ginecoobstétricos')),
                ('habito', models.TextField(blank=True, null=True, verbose_name='Hábitos')),
                ('antecedente_medicamento', models.TextField(blank=True, null=True, verbose_name='Antecedentes sobre uso de medicamentos.')),
                ('alergia', models.TextField(blank=True, null=True, verbose_name='Alergias')),
                ('antecedente_personal_social', models.TextField(blank=True, null=True, verbose_name='Antecedentes sociales y personales.')),
                ('atecedente_familiar', models.TextField(blank=True, null=True, verbose_name='Antecedentes familiares')),
                ('inmunizacion', models.TextField(blank=True, null=True, verbose_name='Inmunizaciones')),
            ],
            options={
                'verbose_name': 'AntecedenteMedico',
                'verbose_name_plural': 'AntecedenteMedicos',
            },
        ),
        migrations.CreateModel(
            name='CaraDental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('abrev', models.CharField(max_length=1)),
                ('css_class', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('horario', models.CharField(choices=[('08:00', '08:00'), ('08:15', '08:15'), ('08:30', '08:30'), ('08:45', '08:45'), ('09:00', '09:00'), ('09:15', '09:15'), ('09:30', '09:30'), ('09:45', '09:45'), ('10:00', '10:00'), ('10:15', '10:15'), ('10:30', '10:30'), ('10:45', '10:45'), ('11:00', '11:00'), ('11:15', '11:15'), ('11:30', '11:30'), ('11:45', '11:45'), ('12:00', '12:00'), ('12:15', '12:15'), ('12:30', '12:30'), ('12:45', '12:45'), ('15:00', '15:00'), ('15:15', '15:15'), ('15:30', '15:30'), ('15:45', '15:45'), ('16:00', '16:00'), ('16:15', '16:15'), ('16:30', '16:30'), ('16:45', '16:45'), ('17:00', '17:00'), ('17:15', '17:15'), ('17:30', '17:30'), ('17:45', '17:45'), ('18:00', '18:00'), ('18:15', '18:15'), ('18:30', '18:30'), ('18:45', '18:45')], max_length=5)),
                ('estado', models.CharField(choices=[('REGISTRADO', 'Registrado'), ('CONFIRMADO', 'Confirmado'), ('CANCELADO', 'Cancelado')], default='REGISTRADO', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('motivo', models.CharField(blank=True, choices=[('Motivo 1', 'Motivo 1'), ('Motivo 2', 'Motivo 2'), ('Motivo 3', 'Motivo 3'), ('Motivo 4', 'Motivo 4'), ('Motivo 5', 'Motivo 5')], max_length=255, null=True, verbose_name='Motivo de la consulta')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
            },
        ),
        migrations.CreateModel(
            name='ConsultaEmergencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Consulta por Emergencia',
                'verbose_name_plural': 'Consultas por Emergencia',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamento',
            },
        ),
        migrations.CreateModel(
            name='DetalleReceta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_venta', models.FloatField(blank=True, null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('importe', models.FloatField(blank=True, null=True)),
                ('dosis', models.IntegerField(blank=True, null=True)),
                ('periodo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Detalle de Receta',
                'verbose_name_plural': 'Detalles de Receta',
            },
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Diagnostico',
                'verbose_name_plural': 'Diagnosticos',
            },
        ),
        migrations.CreateModel(
            name='DiagnosticoConsulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atencion.Consulta')),
                ('diagnostico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atencion.Diagnostico')),
            ],
            options={
                'verbose_name': 'Diagnostico por Consulta',
                'verbose_name_plural': 'Diagnostico Consultas',
            },
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Distrito',
                'verbose_name_plural': 'Distrito',
            },
        ),
        migrations.CreateModel(
            name='FuncionesVitales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frecuencia_cardiaca', models.IntegerField()),
                ('frecuencia_respiratoria', models.IntegerField()),
                ('presion_arterial', models.IntegerField()),
                ('temperatura', models.IntegerField()),
                ('peso', models.IntegerField()),
                ('talla', models.IntegerField()),
                ('masa_corporal', models.IntegerField()),
                ('diagnostico_mc', models.CharField(choices=[('PesoBajo', 'Peso Bajo'), ('PesoNormal', 'Peso Normal'), ('Sobrepeso', 'Sobre peso'), ('Obesidad', 'Obesidad'), ('ObesidadSevera', 'Obesidad Severa')], default='PesoNormal', max_length=15)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atencion.Consulta')),
            ],
            options={
                'verbose_name': 'Funciones Vitales',
                'verbose_name_plural': 'Funciones Vitales',
            },
        ),
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('motivo_consulta', models.TextField(null=True)),
                ('riesgo', models.TextField(null=True)),
                ('anamnesis_atencion_medica', models.BooleanField(default=False, verbose_name='¿Ha estado bajo atención médica en los últimos años?')),
                ('anamnesis_alergia', models.BooleanField(default=False, verbose_name='¿Es alérgico a la penicilina u otros medicamentos?')),
                ('anamnesis_enfermedad', models.BooleanField(default=False, verbose_name='¿Padece alguna enfermedad?')),
                ('anamnesis_embarazo', models.BooleanField(default=False, verbose_name='¿Se encuentra embarazada?')),
                ('anamnesis_otros', models.TextField(blank=True, null=True, verbose_name='Ectoscopía')),
                ('antecedentes_diabetes', models.BooleanField(default=False, verbose_name='Diabetes')),
                ('antecedentes_tuberculosis', models.BooleanField(default=False, verbose_name='Tuberculosis')),
                ('antecedentes_enf_renal', models.BooleanField(default=False, verbose_name='Enf. Renal')),
                ('antecedentes_anemia', models.BooleanField(default=False, verbose_name='Anemia')),
                ('antecedentes_fiebre_reumatica', models.BooleanField(default=False, verbose_name='Fiebre Reumatica')),
                ('antecedentes_hemorragias', models.BooleanField(default=False, verbose_name='Hemorragias')),
                ('antecedentes_infecciones', models.BooleanField(default=False, verbose_name='Infecciones')),
                ('antecedentes_enf_cardio', models.BooleanField(default=False, verbose_name='Enf. Cardiovascular')),
                ('antecedentes_alerg_penicilina', models.BooleanField(default=False, verbose_name='Alergia a la Penicilina')),
                ('antecedentes_enf_hepaticas', models.BooleanField(default=False, verbose_name='Enf.Hepaticas')),
                ('examen_atm', models.CharField(max_length=100)),
                ('examen_atm_ganglios', models.CharField(max_length=100)),
                ('examen_labios', models.CharField(max_length=100)),
                ('examen_vestibulo', models.CharField(max_length=100)),
                ('examen_lengua', models.CharField(max_length=100)),
                ('examen_paladar', models.CharField(max_length=100)),
                ('examen_piso_boca', models.CharField(max_length=100)),
                ('examen_periodonto', models.CharField(max_length=100)),
                ('examen_otros', models.TextField(blank=True, max_length=150, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Historia',
                'verbose_name_plural': 'Historias',
            },
        ),
        migrations.CreateModel(
            name='HistoriaDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('tratamiento', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hemoglobina', models.IntegerField()),
                ('endocritos', models.IntegerField()),
                ('globulos_rojos', models.IntegerField()),
                ('globulos_blancos', models.IntegerField()),
                ('tipo_sangre', models.CharField(max_length=10)),
                ('historia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atencion.Historia')),
            ],
            options={
                'verbose_name': 'Prueba de Laboratorio',
                'verbose_name_plural': 'Pruebas de Laboratorio',
            },
        ),
        migrations.CreateModel(
            name='Odontograma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('plan_tratamiento', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('historia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atencion.Historia')),
            ],
        ),
        migrations.CreateModel(
            name='OdontogramaPieza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuadrante', models.IntegerField(choices=[(1, 'Superior Derecho'), (2, 'Superior Izquierdo'), (3, 'Inferior Derecho'), (4, 'Inferior Izquierdo')], default=1)),
                ('orden', models.IntegerField()),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciclo', models.CharField(max_length=10, unique=True)),
                ('fecha', models.DateField()),
            ],
            options={
                'verbose_name': 'Periodo',
                'verbose_name_plural': 'Periodos',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=40)),
                ('apellido_paterno', models.CharField(max_length=40)),
                ('apellido_materno', models.CharField(max_length=40)),
                ('dni', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('estado_civil', models.CharField(blank=True, choices=[('Soltero', 'Soltero'), ('Casado', 'Casado'), ('Divorciado', 'Divorciado'), ('Viudo', 'Viudo'), ('Conviviente', 'Conviviente')], max_length=20, null=True)),
                ('sexo', models.CharField(choices=[('Femenino', 'Femenino'), ('Masculino', 'Masculino')], max_length=19)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('ocupacion', models.CharField(blank=True, choices=[('Medico', 'Medico'), ('Estudiante', 'Estudiante'), ('Docente', 'Docente'), ('TrabajadorIndependiente', 'Trabajador Independiente')], max_length=35, null=True)),
                ('direccion_actual', models.CharField(max_length=100)),
                ('contacto', models.CharField(blank=True, max_length=10, null=True)),
                ('nro_historia', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('con_historia', models.BooleanField(default=False)),
                ('estado', models.BooleanField(default=True)),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atencion.Departamento')),
                ('distrito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atencion.Distrito')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
            },
        ),
        migrations.CreateModel(
            name='PiezaDental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('abrev', models.CharField(max_length=5, unique=True)),
                ('orden', models.IntegerField()),
                ('imagen', models.ImageField(upload_to='piezas')),
                ('tipo', models.CharField(choices=[('Permanente', 'Permanente'), ('Temporal', 'Temporal')], default='Permanente', max_length=100)),
                ('cuadrante', models.IntegerField(choices=[(1, 'Superior Derecho'), (2, 'Superior Izquierdo'), (3, 'Inferior Derecho'), (4, 'Inferior Izquierdo')], default=1)),
                ('cara_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cara_1', to='atencion.CaraDental')),
                ('cara_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cara_2', to='atencion.CaraDental')),
                ('cara_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cara_3', to='atencion.CaraDental')),
                ('cara_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cara_4', to='atencion.CaraDental')),
                ('cara_5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cara_5', to='atencion.CaraDental')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(unique=True)),
                ('descripcion', models.CharField(max_length=100)),
                ('stock', models.IntegerField()),
                ('precio_compra', models.FloatField()),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atencion.Departamento')),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincia',
            },
        ),
        migrations.CreateModel(
            name='ReporteAtencion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('dia', models.IntegerField()),
                ('pacientes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atencion.Consulta')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_colegio', models.CharField(blank=True, max_length=10, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atencion.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('recomendacion', models.TextField()),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atencion.Consulta')),
            ],
            options={
                'verbose_name': 'Tratamiento',
                'verbose_name_plural': 'Tratamientos',
            },
        ),
        migrations.CreateModel(
            name='TratamientoDental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('css_class', models.CharField(max_length=50)),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Unidad de Medida',
                'verbose_name_plural': 'Unidades de Medida',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('apellidos', models.CharField(max_length=60)),
                ('dni', models.CharField(max_length=10)),
                ('sexo', models.CharField(choices=[('Femenino', 'Femenino'), ('Masculino', 'Masculino')], max_length=20)),
                ('ocupacion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=10)),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='persona',
            name='provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atencion.Provincia'),
        ),
        migrations.AddField(
            model_name='odontogramapieza',
            name='cara_1_tratamiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tratamiento_cara_1', to='atencion.TratamientoDental'),
        ),
        migrations.AddField(
            model_name='odontogramapieza',
            name='cara_2_tratamiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tratamiento_cara_2', to='atencion.TratamientoDental'),
        ),
        migrations.AddField(
            model_name='odontogramapieza',
            name='cara_3_tratamiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tratamiento_cara_3', to='atencion.TratamientoDental'),
        ),
        migrations.AddField(
            model_name='odontogramapieza',
            name='cara_4_tratamiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tratamiento_cara_4', to='atencion.TratamientoDental'),
        ),
        migrations.AddField(
            model_name='odontogramapieza',
            name='cara_5_tratamiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tratamiento_cara_5', to='atencion.TratamientoDental'),
        ),
        migrations.AddField(
            model_name='odontogramapieza',
            name='odontograma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atencion.Odontograma'),
        ),
        migrations.AddField(
            model_name='odontogramapieza',
            name='pieza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atencion.PiezaDental'),
        ),
        migrations.AddField(
            model_name='odontogramapieza',
            name='tratamiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tratamiento_pieza', to='atencion.TratamientoDental'),
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atencion.Periodo'),
        ),
        migrations.AddField(
            model_name='historiadetalle',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atencion.Trabajador', verbose_name='Doctor'),
        ),
        migrations.AddField(
            model_name='historiadetalle',
            name='historia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atencion.Historia'),
        ),
        migrations.AddField(
            model_name='historia',
            name='persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='atencion.Persona'),
        ),
        migrations.AddField(
            model_name='distrito',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atencion.Provincia'),
        ),
        migrations.AddField(
            model_name='detallereceta',
            name='presentacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atencion.UnidadMedida'),
        ),
        migrations.AddField(
            model_name='detallereceta',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atencion.Producto'),
        ),
        migrations.AddField(
            model_name='detallereceta',
            name='tratamiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atencion.Tratamiento'),
        ),
        migrations.AddField(
            model_name='consultaemergencia',
            name='historia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atencion.Historia'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='historia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atencion.Historia'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atencion.Trabajador', verbose_name='Doctor'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atencion.Usuario'),
        ),
        migrations.AddField(
            model_name='antecedentemedico',
            name='historia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atencion.Historia'),
        ),
        migrations.AlterUniqueTogether(
            name='consulta',
            unique_together=set([('horario', 'fecha', 'trabajador')]),
        ),
    ]
