# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-11-16 23:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atencion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='odontograma',
            old_name='observaciones',
            new_name='informe',
        ),
    ]
