# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-11-17 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atencion', '0006_auto_20171116_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamenesAuxiliares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('de_aleta_mordida', models.BooleanField(default=False, verbose_name='De aleta mordida')),
                ('periapical', models.BooleanField(default=False, verbose_name='Periapical')),
                ('panoramica', models.BooleanField(default=False, verbose_name='Panorámica')),
                ('oclusal', models.BooleanField(default=False, verbose_name='Oclusal')),
                ('examenes_auxiliares_otros', models.TextField(blank=True, null=True, verbose_name='Otros')),
                ('montados_asa', models.BooleanField(default=False, verbose_name='Montados en ASA')),
                ('sin_montar', models.BooleanField(default=False, verbose_name='Sin montar')),
            ],
        ),
    ]
