# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-11-17 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atencion', '0008_auto_20171116_2107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examenesauxiliares',
            old_name='examenes_auxiliares_otros',
            new_name='examenes_modelos_otros',
        ),
        migrations.AddField(
            model_name='examenesauxiliares',
            name='examenes_radigrafia_otros',
            field=models.TextField(blank=True, null=True, verbose_name='Otros'),
        ),
    ]
