# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-11-17 04:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atencion', '0009_auto_20171116_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='examenesauxiliares',
            name='odontograma',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='atencion.Odontograma'),
            preserve_default=False,
        ),
    ]
