# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-11-27 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atencion', '0011_piezadental_ausente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piezadental',
            name='ausente',
        ),
        migrations.AddField(
            model_name='odontogramapieza',
            name='ausente',
            field=models.BooleanField(default=False),
        ),
    ]
