# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-11-27 02:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atencion', '0014_odontogramapieza_pieza_usente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='odontogramapieza',
            old_name='pieza_usente',
            new_name='cara_0_tratamiento',
        ),
    ]
